
name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push
        env:
          ECR_REPOSITORY: inspectionwale/pdf-generator
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr create-repository --repository-name $ECR_REPOSITORY || true
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG backend/pdf-generator
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
